import type { Behavior, PageContext } from './GhostChat';
export class BehaviorTracker {
  private points:Behavior['trajectory']=[];private events:Behavior['events']=[];
  private lastSample=0;private lastActivity=performance.now();private entered=performance.now();private hover='';private lastView='';private dwell=0;private reason='';private lastScroll=0;
  private push(e:Behavior['events'][number]){this.events.push(e);this.events=this.events.slice(-60);this.reason=e.type+':'+e.target;}
  pointer=(e:PointerEvent)=>{const now=performance.now();this.lastActivity=now;const id=(e.target as Element).closest<HTMLElement>('[data-agent-id]')?.dataset.agentId||'';if(id!==this.hover){if(this.hover)this.push({type:'hover',target:this.hover,duration:now-this.entered,value:0});this.hover=id;this.entered=now;}if(now-this.lastSample<100)return;this.lastSample=now;this.points.push({x:Math.max(0,Math.min(1,e.clientX/innerWidth)),y:Math.max(0,Math.min(1,e.clientY/innerHeight)),t:now});this.points=this.points.filter(p=>now-p.t<=30000);};
  click=(e:Event)=>{this.lastActivity=performance.now();const target=(e.target as Element).closest<HTMLElement>('[data-agent-id]')?.dataset.agentId;if(target)this.push({type:'click',target,duration:0,value:0});};
  scroll=(e:Event)=>{this.lastActivity=performance.now();if(performance.now()-this.lastScroll<500)return;this.lastScroll=performance.now();const el=e.target as HTMLElement;if(!el.classList?.contains('content-scroll'))return;this.push({type:'scroll',target:el.closest<HTMLElement>('[data-window-id]')?.dataset.windowId||'desktop',duration:0,value:el.scrollHeight>el.clientHeight?el.scrollTop/(el.scrollHeight-el.clientHeight):0});};
  visibility=()=>{this.entered=performance.now();this.hover='';this.dwell=0;this.push({type:'visibility',target:'page',duration:0,value:document.hidden?0:1});};
  attach(){document.addEventListener('pointermove',this.pointer,{passive:true});document.addEventListener('click',this.click);document.addEventListener('scroll',this.scroll,true);document.addEventListener('visibilitychange',this.visibility);return()=>{document.removeEventListener('pointermove',this.pointer);document.removeEventListener('click',this.click);document.removeEventListener('scroll',this.scroll,true);document.removeEventListener('visibilitychange',this.visibility);};}
  tick(context:PageContext){if(document.hidden)return;const view=context.activeWindow+':'+context.aboutTab+':'+context.targets.filter(t=>t.visible&&t.id.includes(':section-')).map(t=>t.id).join(',');if(view!==this.lastView){this.lastView=view;this.dwell=0;this.push({type:'visit',target:(context.activeWindow||'desktop')+(context.activeWindow==='about'?':'+context.aboutTab:''),duration:0,value:0});}this.dwell++;if(this.dwell===15)this.reason='dwell:'+view;if(Math.floor((performance.now()-this.lastActivity)/1000)===20)this.reason='idle';}
  consumeReason(){const r=this.reason;this.reason='';return r;}
  snapshot():Behavior{const now=performance.now();const points=this.points.filter(p=>now-p.t<=30000);const selected=points.length<=20?points:Array.from({length:20},(_,i)=>points[Math.floor(i*(points.length-1)/19)]);const events=this.events.slice(-59);if(this.hover&&!document.hidden)events.push({type:'hover',target:this.hover,duration:now-this.entered,value:0});return {events,trajectory:selected,idleSeconds:Math.min(7200,(now-this.lastActivity)/1000)};}
}
