import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button', { name: 'About', exact: true }).click();
const about = page.getByRole('region', { name: 'About', exact: true });
await about.getByRole('heading', { name: /Xiaoheng Hu/ }).waitFor();
await page.waitForTimeout(950);
await page.screenshot({ path: 'test-results/about-profile.png' });
await about.getByRole('button', { name: 'Experience', exact: true }).click();
for (const company of ['Infineon Technologies', 'Innocoso', 'Huawei']) assert(await about.getByRole('heading', { name: company, exact: true }).count());
await about.locator('summary').first().click();
assert.match(await about.innerText(), /15\+/);
await page.screenshot({ path: 'test-results/about-experience.png' });
await about.getByRole('button', { name: 'Education', exact: true }).click();
assert.match(await about.innerText(), /Technical University of Munich/);
await about.getByRole('button', { name: 'Toolkit', exact: true }).click();
assert.match(await about.innerText(), /LangGraph/);
await about.getByRole('button', { name: 'Research & projects', exact: true }).click();
assert.equal(await about.locator('.resume-entry').count(), 6);
assert(!/Horemans|338 4004|tailoringGuidance/.test(await about.innerText()));
await page.getByRole('button', { name: 'close About', exact: true }).click();
await page.getByRole('button', { name: 'Projects', exact: true }).click();
const projects = page.getByRole('region', { name: 'Projects', exact: true });
assert.equal(await projects.locator('.project-entry').count(), 4);
await projects.locator('.project-entry img').first().evaluate(img => img.complete && img.naturalWidth ? Promise.resolve() : new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; }));
await page.waitForTimeout(950);
await page.screenshot({ path: 'test-results/projects-list.png' });
for (let i = 0; i < 4; i++) {
  await projects.locator('.project-entry').nth(i).click();
  const detail = page.locator('.desktop-window.active');
  await detail.locator('.markdown-content h2').first().waitFor();
  assert(!/Portfolio copy|网页文案草案|待补充信息/.test(await detail.innerText()));
  const pdf = await detail.locator('.project-detail-nav a').getAttribute('href');
  assert((await page.request.head(new URL(pdf, page.url()).href)).ok());
  const images = await detail.locator('.markdown-content img').evaluateAll(items => items.map(i => i.src));
  assert(images.length >= 2);
  for (const src of images) assert((await page.request.head(src)).ok(), src);
  if (i < 3) { const src = await detail.locator('video').getAttribute('src'); assert((await page.request.head(new URL(src, page.url()).href)).ok()); }
  if (i === 0) await page.screenshot({ path: 'test-results/project-detail.png' });
  await detail.getByRole('button', { name: /^close / }).click();
}
await page.getByRole('button', { name: 'Switch to Chinese' }).click();
await page.getByRole('region', { name: '项目', exact: true }).locator('.project-entry').first().click();
assert.match(await page.locator('.desktop-window.active .project-detail').innerText(), /稀疏匹配/);
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(300);
assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
assert(await page.locator('.desktop-window.active .content-scroll').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
await page.screenshot({ path: 'test-results/project-mobile.png' });
await page.locator('.desktop-window.active').getByRole('button', { name: /^关闭/ }).click();
await page.getByRole('button', { name: '关闭项目' }).click();
await page.getByRole('button', { name: '关于', exact: true }).click();
await page.getByRole('region', { name: '关于', exact: true }).getByRole('button', { name: '工作经历' }).click();
assert.match(await page.getByRole('region', { name: '关于', exact: true }).innerText(), /系统工程师/);
await page.screenshot({ path: 'test-results/about-mobile.png' });
assert.deepEqual(errors, []);
await browser.close();
console.log('PASS: About sections, bilingual copy, four Markdown projects, all media/PDF URLs, mobile scroll, no runtime errors.');
import './test-workspace.mjs';
