import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
await page.goto('http://127.0.0.1:5173');
await page.locator('.boot-overlay').waitFor({ state: 'detached' });
await page.waitForFunction(() => [...document.images].every(i => i.complete && i.naturalWidth));
await page.mouse.move(5, 5);
await page.waitForTimeout(1100);
const screen = page.locator('.monitor-screen');
const initial = await screen.boundingBox();
const iconWidth = await page.locator('.folder-icon').first().evaluate(e => e.offsetWidth);
assert.equal(iconWidth, 23);
const occupancy = await page.evaluate(() => {
  const first = document.querySelector('.folder').getBoundingClientRect();
  const all = document.querySelectorAll('.folder');
  const last = all[3].getBoundingClientRect();
  const desktop = document.querySelector('.desktop-area').getBoundingClientRect();
  return (last.bottom - first.top) / desktop.height;
});
assert(occupancy < .52);
await page.screenshot({ path: 'test-results/focus-outside.png' });
await page.mouse.move(initial.x + initial.width / 2, initial.y + initial.height / 2);
await page.waitForTimeout(1500);
const zoomed = await screen.boundingBox();
assert(zoomed.width > initial.width * 1.2);
assert(zoomed.x >= 0 && zoomed.y >= 0 && zoomed.x + zoomed.width <= 1440 && zoomed.y + zoomed.height <= 960);
assert.equal(await page.locator('.folder-icon').first().evaluate(e => e.offsetWidth), iconWidth);
const ghost = await page.locator('.ghost-overlay').boundingBox();
assert(ghost.x > 1280);
await page.screenshot({ path: 'test-results/focus-inside.png' });
await page.waitForTimeout(1000);
assert(Math.abs((await screen.boundingBox()).width - zoomed.width) < 1);
await page.mouse.move(5, 5);
await page.waitForTimeout(1200);
assert(Math.abs((await screen.boundingBox()).width - initial.width) < 1);
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.mouse.move(initial.x + initial.width / 2, initial.y + initial.height / 2);
await page.waitForTimeout(100);
assert.equal(await page.locator('.stage').evaluate(e => getComputedStyle(e).transitionDuration), '0s');
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 390, height: 844 });
await page.mouse.move(180, 300);
await page.waitForTimeout(100);
assert.equal(await page.locator('.stage').evaluate(e => getComputedStyle(e).transform), 'none');
console.log(JSON.stringify({ result: 'PASS', initial, zoomed, iconWidth, occupancy, ghostX: ghost.x }));
await browser.close();
import './test-workspace.mjs';
