import { useDesktop } from '../features/ghost/DesktopContext';
import type { Language } from '../model';
import profile from '../../../content/profile.json';
import { experienceZh, researchZh, skillLabels } from './translations';

export function Tags({ values }: { values: string[] }) { return <div className="content-tags">{values.map(value => <span key={value}>{value}</span>)}</div>; }
export function ExperienceContent({ language }: { language: Language }) {
  return <div className="resume-timeline">{profile.experience.map((job, i) => <article className="resume-entry" key={job.company}><span className="content-kicker">{job.date} · {job.location}</span><h2>{job.company}</h2><h3>{language === 'zh' ? experienceZh[i].role : job.role}</h3><p>{language === 'zh' ? experienceZh[i].summary : job.summary}</p><details><summary>{language === 'en' ? 'Responsibilities & impact' : '工作内容与成果'}</summary><ul>{(language === 'zh' ? experienceZh[i].highlights : job.highlights).map(line => <li key={line}>{line}</li>)}</ul></details><Tags values={job.technologies} /></article>)}</div>;
}
export function ContactContent({ language }: { language: Language }) {
  return <div className="contact-content"><span className="content-kicker">LET’S CONNECT</span><h1>{language === 'en' ? 'Say hello.' : '来打个招呼。'}</h1><p>{language === 'en' ? 'For conversations about software, AI and useful things to build.' : '聊聊软件、AI，以及值得一起构建的东西。'}</p><a href={`mailto:${profile.email}`}>{profile.email} ↗</a><a href={profile.linkedIn} target="_blank" rel="noopener noreferrer">LinkedIn / Xiaoheng Hu ↗</a><p className="content-muted">{language === 'en' ? profile.location : '德国 · 慕尼黑'}</p></div>;
}
export function AboutContent({ language }: { language: Language }) {
  const desktop = useDesktop();
  const tab = desktop.state.aboutTab, setTab = desktop.selectTab;
  const tabs = [['profile', 'Profile', '简介'], ['experience', 'Experience', '工作经历'], ['education', 'Education', '教育'], ['skills', 'Toolkit', '技能'], ['research', 'Research & projects', '研究与项目']];
  return <div className="about-content"><header className="profile-header"><span className="content-kicker">ABOUT / XIAOHENG HU</span><h1>胡晓亨 <span>Xiaoheng Hu</span></h1><p className="profile-role">{language === 'en' ? 'Software Engineer · AI & Fullstack · Platform' : '软件工程师 · AI 与全栈开发 · 平台工程'}</p><p className="content-muted">{language === 'en' ? profile.location : '德国 · 慕尼黑'} <span aria-hidden="true"> / </span><a href={`mailto:${profile.email}`}>Email ↗</a> <a href={profile.linkedIn} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></p></header><nav className="content-tabs" aria-label={language === 'en' ? 'About sections' : '关于页面分区'}>{tabs.map(([id, en, zh]) => <button key={id} data-agent-id={`about-tab:${id}`} aria-pressed={tab === id} onClick={() => setTab(id)}>{language === 'en' ? en : zh}</button>)}</nav>
    <div className="about-section" key={tab} data-agent-id={`about:${tab}`} data-agent-label={tab}>
    {tab === 'profile' && <><p className="profile-intro">{language === 'en' ? profile.summary : '我的经历横跨全栈产品开发、AI / 大模型应用、内部开发者平台、CI/CD 和云部署，也涉及实验产物追踪与数据工作流。喜欢把复杂技术连接到真实使用场景，构建能够交付、使用和持续维护的软件。'}</p><div className="profile-focus"><article><span>01 / BUILD</span><h2>Fullstack</h2><p>{language === 'en' ? 'Enterprise workflows, APIs, data models and operational dashboards.' : '企业业务流程、API、数据模型与运营看板。'}</p></article><article><span>02 / CONNECT</span><h2>AI & Agents</h2><p>{language === 'en' ? 'RAG, multi-agent systems and evaluation-driven LLM applications.' : 'RAG、多智能体协作与基于评估的大模型应用。'}</p></article><article><span>03 / SHIP</span><h2>Platform</h2><p>{language === 'en' ? 'Developer platforms, reproducible builds and cloud delivery.' : '开发者平台、可复现构建与云端交付。'}</p></article></div><h2>{language === 'en' ? 'Languages' : '语言'}</h2><Tags values={Object.entries(profile.languages).map(([name, level]) => `${name} · ${level}`)} /></>}
    {tab === 'experience' && <ExperienceContent language={language} />}
    {tab === 'education' && profile.education.map((item, i) => <article className="resume-entry" key={item.school}><span className="content-kicker">{item.date} · {item.location}</span><h2>{language === 'zh' ? ['慕尼黑工业大学', '武汉理工大学'][i] : item.school}</h2><h3>{language === 'zh' ? ['信息学硕士 · M.Sc. Informatics', '软件工程学士 · B.Sc. Software Engineering'][i] : item.title}</h3><p>{language === 'en' ? 'Grade' : '成绩'}: {item.grade}</p><Tags values={item.courses} /></article>)}
    {tab === 'skills' && Object.entries(profile.skills).map(([key, values]) => <section className="skill-section" key={key}><h2>{skillLabels[key][language === 'en' ? 0 : 1]}</h2><Tags values={values} /></section>)}
    {tab === 'research' && profile.projects.map((item, i) => <article className="resume-entry" key={item.title}><span className="content-kicker">{item.date} · {item.org}</span><h2>{language === 'zh' ? researchZh[i].title : item.title}</h2><p>{language === 'zh' ? researchZh[i].summary : item.summary}</p><details><summary>{language === 'en' ? 'Project details' : '完整项目记录（英文）'}</summary><ul>{item.details.map(line => <li key={line}>{line}</li>)}</ul></details><Tags values={item.technologies} /></article>)}
    </div></div>;
}
