import { useEffect, useRef } from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { Language } from '../model';
import { projects, projectCopy, assetUrl } from './projects';
import { Tags } from './AboutContent';

export function ProjectsContent({ language, visible, projectId, onSelect }: { language: Language; visible: boolean; projectId?: string; onSelect: (id: string | null) => void }) {
  const selected = projectId, setSelected = onSelect;
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!visible) root.current?.querySelectorAll('video').forEach(video => video.pause()); }, [visible]);
  const project = projects.find(item => item.id === selected);
  useEffect(() => { const scroller = root.current?.closest('.content-scroll'); if (scroller) scroller.scrollTop = 0; }, [selected, language]);
  if (!project) return <div ref={root} className="projects-content"><header className="collection-header"><span className="content-kicker">SELECTED WORK / 04</span><h1>{language === 'en' ? 'Things I’ve built.' : '做过的一些东西。'}</h1><p>{language === 'en' ? 'From visual perception and trusted systems to creative tools.' : '从视觉感知与可信系统，到 AI 内容编辑工具。'}</p></header><div className="project-collection">{projects.map((item, index) => <button className="project-entry" key={item.id} data-agent-id={`project-card:${item.id}`} data-agent-label={language === 'en' ? item.title : item.zh} onClick={() => setSelected(item.id)}><div className="project-thumb"><img src={assetUrl(`assets/${item.image}`)} alt={language === 'en' ? item.title : item.zh} loading="lazy" /><span>0{index + 1}</span></div><div className="project-entry-copy"><span className="content-kicker">{item.category}</span><h2>{language === 'en' ? item.title : item.zh}</h2><p>{projectCopy(item.id, language).summary}</p><span className="project-read">{language === 'en' ? 'Explore project' : '查看项目'} →</span></div></button>)}</div></div>;
  const copy = projectCopy(project.id, language);
  const headingOffsets = [...copy.body.matchAll(/^## /gm)].map(match => match.index);
  const video = project.video ? assetUrl(`videos/${project.video}`) : undefined;
  return <div ref={root} className="project-detail" data-agent-id={`project:${project.id}`} data-agent-label={language === 'en' ? project.title : project.zh} data-agent-excerpt={copy.summary}><div className="project-detail-nav"><button onClick={() => setSelected(null)}>← {language === 'en' ? 'All projects' : '全部项目'}</button><a href={assetUrl(`pdf/${project.pdf}`)} target="_blank" rel="noopener noreferrer">PDF ↗</a></div><span className="content-kicker">{project.category}</span><h1>{language === 'en' ? project.title : project.zh}</h1><p className="project-summary">{copy.summary}</p><Tags values={project.tags} />{video && <figure className="project-video"><video controls preload="none" playsInline poster={assetUrl(`assets/${project.image}`)} src={video} aria-label={language === 'en' ? `${project.title} demo` : `${project.zh}演示`} /><figcaption>{language === 'en' ? 'Project demonstration' : '项目演示'}</figcaption></figure>}<article className="markdown-content"><Markdown remarkPlugins={[remarkGfm]} skipHtml urlTransform={url => assetUrl(url) ?? (/^https?:\/\//.test(url) ? url : '')} components={{ h2: ({ node, children }) => <h2 data-agent-id={`project:${project.id}:section-${headingOffsets.indexOf(node?.position?.start.offset ?? -1)}`} data-agent-label={String(children)}>{children}</h2>, img: ({ src, alt }) => src ? <span className="project-figure"><a href={src} target="_blank" rel="noopener noreferrer"><img src={src} alt={alt ?? ''} loading="lazy" /></a><span>{alt}</span></span> : null, a: ({ children, href }) => href ? <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a> : <span>{children}</span> }}>{copy.body}</Markdown></article><button className="content-back" onClick={() => setSelected(null)}>← {language === 'en' ? 'Back to projects' : '返回项目列表'}</button></div>;
}
